[package]
name = "language"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
criterion = "^0.3.5"

[profile.release]
lto = "fat"
codegen-units = 1
# lowers size of file but can cause problems with some libraries
panic = "abort"

[[bench]]
name = "bench" 
harness = false